// src/shell/components/toolbox/Toolbox.vue
<template>
  <ToolboxAccordion :groups = "groups">
  </ToolboxAccordion>
</template>

<script>
import ToolboxAccordion from './ToolboxAccordion.vue'

export default {
  name: 'Toolbox',
  components:{
    ToolboxAccordion,
  },
  props:{
    groups:{ default:[] }, 
  },
  data () {
    return {
    }
  },

}
</script>

<style>
  .element-title{
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    cursor: default;
    color: #c2c2c2;
    font-size: 13px;
    padding:5px 10px;
    padding-left:20px;
    margin:3px;
    display: flex;
    flex-flow: row;
    align-items: center;
  }

  .element-title i{
    margin-right: 5px;
    margin-top:1px;
  }

  .toolbox-element .element-title:hover{
    background: rgba(255,255,255,0.05)

  }

  .toolbox-element{
    padding-left: 0;
    line-height: 20px;
}

  .toolbox-element .pop-content{
    position: absolute;
    top:70px;
    left:100%;
    width: 320px;
    padding:10px;
    background: #eee;
  }
  .toolbox-element .pop-content img{
    width: 100%;
  }
</style>

// packages/rxdrag/editor/react-antd-shell-inline/src/components/Toolbox/index.tsx
import { memo } from "react"
import styled from "styled-components"
import { boxShadow } from "../utils"
import { CloseOutlined } from "@ant-design/icons"
import { Button } from "antd"

const Container = styled.div`
  position: fixed;
  height:calc(100vh - 120px);
  width: 200px;
  box-shadow: ${boxShadow};
  top: 50%;
  transform: translateY(-50%);
  left:8px;
  border: solid 1px ${props => props.theme?.token?.colorBorder};
  background-color: ${props => props.theme?.token?.colorBgContainer};
  border-radius: 8px;
  display: flex;
  flex-flow: column;
`

const Title = styled.div`
  display: flex;
  padding: 8px 16px;
  padding-right: 8px;
  justify-content: space-between;
  align-items: center;
  border-bottom: solid 1px ${props => props.theme?.token?.colorBorder};
`

export const Toolbox = memo(() => {
  return (
    <Container>
      <Title>
        <span>
          工具箱
        </span>
        <Button type="text" size="small" icon={<CloseOutlined />} />
      </Title>
    </Container>
  )
})
